controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

pdf_generate:
    path: /pdf
    controller: App\Controller\PdfController::generatePdf